version: '2'
services:
  fpm:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/wordpress

  nginx:
    image: nginx
    volumes:
      - ./:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - fpm
    environment:
      - VIRTUAL_HOST=simowitz.test

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
