FROM toxicsalt/wordpress
ARG UID
ARG GID
RUN echo "http://nl.alpinelinux.org/alpine/edge/community/" >> /etc/apk/repositories
RUN apk update && apk add --no-cache shadow
RUN usermod -u $UID www-data && groupmod -g $GID www-data
