version: '2'

volumes:
  app:

services:
  fpm:
    build:
      args:
        - ACF_PRO_KEY
      context: ./
    depends_on:
      - db
    env_file:
      - docker/env/fpm.env
      - docker/env/db.env
    image: simowitz.com
    volumes:
      - app:/var/www/html

  nginx:
    image: nginx
    volumes:
      - app:/var/www/html
      - ./site.production.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - fpm
    ports:
      - 5000:80

  db:
    image: mariadb
    ports:
      - 3306:3306
    env_file:
      - docker/env/db.env
