version: '2'

services:
  fpm:
    build:
      context: ./
      dockerfile: docker/images/bedrock/Dockerfile.development
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    env_file:
      - docker/env/fpm.env
      - docker/env/db.env

  nginx:
    image: nginx
    volumes:
      - ./:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - fpm
    ports:
      - 5000:80

  db:
    image: mariadb
    ports:
      - 3306:3306
    env_file:
      - docker/env/db.env
